version: '3.0'

services:
  nginx-rmtp:
    build:
      dockerfile: Dockerfile
    # image: dhb52/nginx-rmtp:latest
    container_name: nginx-rmtp
    ports:
      - 1935:1935/tcp
      - 8081:8081/tcp
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/records:/records
    restart: always