version: '3.0'

services:
  nginx-http-flv:
    build:
      dockerfile: Dockerfile
    # image: dhb52/nginx-rmtp:latest
    container_name: nginx-http-flv
    ports:
      - 1935:1935/tcp
      - 8080:80/tcp
    volumes:
      - $PWD/http-flv/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/http-flv/tmp:/tmp
      - $PWD/http-flv/www:/var/www
      - $PWD/http-flv/logs:/usr/local/nginx/logs
    restart: always