version: '3.0'

services:
  nginx-http-flv:
    build:
      dockerfile: Dockerfile
    container_name: nginx-http-flv
    ports:
      - 1935:1935/tcp
      - 8080:80/tcp
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/data/flv:/data/flv
      - $PWD/data/hls:/data/hls
      - $PWD/data/www:/data/www
      - $PWD/data/www/rtmp:/data/www/rtmp
      - $PWD/data/logs:/usr/local/nginx/logs
    restart: always